export enum jurisdictions{
    "United States",
    "China",
    "Japan",
    "Germany",
    "India",
    "United Kingdom",
    "France",
    "Russia",
    "Canada",
    "Italy",
    "Brazil",
    "Australia",
    "South Korea",
    "Mexico",
    "Spain",
    "Indonesia",
    "Saudi Arabia",
    "Netherlands",
    "Turkey",
    "Switzerland",
    "Poland",
    "Argentina",
    "Sweden",
    "Norway",
    "Belgium",
    "Ireland",
    "Israel",
    "United Arab Emirates",
    "Thailand",
    "Nigeria",
    "Egypt",
    "Austria",
    "Singapore",
    "Bangladesh",
    "Vietnam",
    "Malaysia",
    "South Africa",
    "Philippines",
    "Denmark",
    "Iran",
    "Pakistan",
    "Hong Kong",
    "Colombia",
    "Romania",
    "Chile",
    "Czech Republic (Czechia)",
    "Finland",
    "Iraq",
    "Portugal",
    "New Zealand",
    "Luxembourg",
    "Qatar",
    "Iceland",
    "Kuwait",
    "Andorra",
    "Brunei",
    "Malta",
    "Macao",
    "Bahamas",
    "Bahrain",
    "Slovenia",
    "Estonia",
    "Lithuania",
    "Oman",
    "Cyprus",
    "Latvia",
    "Greece",
    "Uruguay",
    "Slovakia",
    "Saint Kitts & Nevis",
    "Barbados",
    "Guyana",
    "Antigua and Barbuda",
    "Trinidad and Tobago",
    "Hungary",
    "Croatia",
    "Panama",
    "Seychelles",
    "Costa Rica",
    "Bulgaria",
    "Maldives",
    "Saint Lucia",
    "Kazakhstan",
    "Dominican Republic",
    "Grenada",
}
  