export const userActivitiesType = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    OTP_GENERATE: "OTP GENERATE",
    LOGIN_ATTEMPT: "LOGIN ATTEMPT",
    WRONG_PASSWORD: "WRONG PASSWORD",
    WRONG_OTP: "WRONG OTP",
    REFRESH_TOKEN: "REFRESH TOKEN",
  };