export enum ConnectorId {
    GOOGLE_WORKSPACE = 'googleWorkspace',
    ATLASSIAN = 'atlassian',
    ONEDRIVE = 'onedrive',
    SHAREPOINT_ONLINE = 'sharepointOnline',
    GMAIL = 'gmail',
    CALENDAR = 'calendar',
    DRIVE = 'drive',
    JIRA = 'jira',
    CONFLUENCE = 'confluence',
    BITBUCKET = 'bitbucket',
    OUTLOOK = 'outlook',
    OUTLOOK_CALENDAR = 'outlookCalendar',
    MICROSOFT_TEAMS = 'microsoftTeams',
    SLACK = 'slack',
    DROPBOX = 'dropbox',
    BOX = 'box',
    UPLOAD = 'upload',
  }
  
  export enum ConnectorNames {
    GOOGLE_WORKSPACE = 'Google Workspace',
    ATLASSIAN = 'Atlassian',
    ONEDRIVE = 'OneDrive',
    SHAREPOINT_ONLINE = 'SharePoint Online',
    GMAIL = 'Gmail',
    CALENDAR = 'Calendar',
    DRIVE = 'Drive',
    JIRA = 'Jira',
    CONFLUENCE = 'Confluence',
    BITBUCKET = 'Bitbucket',
    OUTLOOK = 'Outlook',
    OUTLOOK_CALENDAR = 'Outlook Calendar',
    MICROSOFT_TEAMS = 'Microsoft Teams',
    SLACK = 'Slack',
    DROPBOX = 'Dropbox',
    BOX = 'Box',
    UPLOAD = 'Uploaded Files',
  }
  
  export const ConnectorIdToNameMap: Record<ConnectorId, string> = {
    [ConnectorId.GOOGLE_WORKSPACE]: ConnectorNames.GOOGLE_WORKSPACE,
    [ConnectorId.ATLASSIAN]: ConnectorNames.ATLASSIAN,
    [ConnectorId.ONEDRIVE]: ConnectorNames.ONEDRIVE,
    [ConnectorId.SHAREPOINT_ONLINE]: ConnectorNames.SHAREPOINT_ONLINE,
    [ConnectorId.GMAIL]: ConnectorNames.GMAIL,
    [ConnectorId.CALENDAR]: ConnectorNames.CALENDAR,
    [ConnectorId.DRIVE]: ConnectorNames.DRIVE,
    [ConnectorId.JIRA]: ConnectorNames.JIRA,
    [ConnectorId.CONFLUENCE]: ConnectorNames.CONFLUENCE,
    [ConnectorId.BITBUCKET]: ConnectorNames.BITBUCKET,
    [ConnectorId.OUTLOOK]: ConnectorNames.OUTLOOK,
    [ConnectorId.OUTLOOK_CALENDAR]: ConnectorNames.OUTLOOK_CALENDAR,
    [ConnectorId.MICROSOFT_TEAMS]: ConnectorNames.MICROSOFT_TEAMS,
    [ConnectorId.SLACK]: ConnectorNames.SLACK,
    [ConnectorId.DROPBOX]: ConnectorNames.DROPBOX,
    [ConnectorId.BOX]: ConnectorNames.BOX,
    [ConnectorId.UPLOAD]: ConnectorNames.UPLOAD,
  };